name: R testthat
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  r-testthat:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq libcurl4-openssl-dev libxml2-dev libssl-dev \
            libfontconfig1-dev libharfbuzz-dev libfribidi-dev libuv1-dev \
            libzip-dev zlib1g-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          r-version: "4.3.3"
          use-public-rspm: true

      - name: Set up renv and restore packages
        uses: r-lib/actions/setup-renv@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          cache-version: 1

      - name: Run testthat
        run: ./run_tests.sh
        shell: bash
